apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-configmap
data:
  enketo-secret: jM91pZkXA5y1C4DrPqh4AE63RyOhZcYItIOSQf2npM7vOMVa8MBPWRkBsgTIThN9
  enketo-less-secret: oobDP8GSvlBBilUYNBJboUA83kd1HHDm
  enketo-api-key: nmP4RvmkmKTJUosLofjOHqFGY3ZcNOwRWdNov4KuSMnrEpibLvGIHQuTcdVoQyo1aOThKEfZK6vNKnJfpQ1JxcgLKZOkPxQ6cBvsCMmTWCxWISZrDyZTlAjaxrbrIGL8 