apiVersion: {{ .Values.persistentvolumeclaim.apiversion }}
kind: PersistentVolumeClaim
metadata:
  labels:
    io.fynarfin.service: enketo-redis-main
  name: enketo-redis-main
  namespace: odk  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
