apiVersion: v1
kind: Service
metadata:
  labels:
    io.fynarfin.service: enketo
  name: enketo
spec:
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8005
  selector:
    io.fynarfin.service: enketo
status:
  loadBalancer: {}
