apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    io.fynarfin.service: enketo-redis-cache
  name: enketo-redis-cache
  namespace: odk  
spec:
  ports:
    - name: "6380"
      port: 6380
      targetPort: 6380
  selector:
    io.fynarfin.service: enketo-redis-cache
status:
  loadBalancer: {}
