apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.fynarfin.service: enketo-redis-main
  name: enketo-redis-main
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
