apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.fynarfin.service: mail-claim0
  name: mail-claim0
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
