apiVersion: {{ .Values.persistentvolumeclaim.apiversion }}
kind: PersistentVolumeClaim
metadata:
  labels:
    io.fynarfin.service: postgres-claim0
  name: postgres-claim0
  namespace: odk  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
