apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-configmap
  namespace: odk  
data:
  enketo-secret: {{ randAlphaNum 64 }}
  enketo-less-secret: {{ randAlphaNum 32 }}
  enketo-api-key: {{ randAlphaNum 128 }} 