# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     io.fynarfin.service: secrets
#   name: secrets
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.fynarfin.service: secrets
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         io.fynarfin.service: secrets
#     spec:
#       containers:
#         - args:
#             - ./generate-secrets.sh
#           image: ntando/odk-central-secrets:latest
#           name: secrets
#           resources:
#             requests:
#               memory: "128Mi"
#               cpu: "256m"
#             limits:
#               memory: "128Mi"
#               cpu: "256m"            
#           volumeMounts:
#             - mountPath: /etc/secrets
#               name: secrets
#       restartPolicy: Always
#       volumes:
#         - name: secrets
#           persistentVolumeClaim:
#             claimName: secrets
# status: {}
