apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    io.fynarfin.service: service
  name: service
  namespace: odk  
spec:
  ports:
    - name: "8383"
      port: 8383
      targetPort: 8383
  selector:
    io.fynarfin.service: service
status:
  loadBalancer: {}
