apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.fynarfin.service: service-claim1
  name: service-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
