apiVersion: v1
kind: Service
metadata:
  labels:
    io.fynarfin.service: service
  name: service
spec:
  ports:
    - name: "8383"
      port: 8383
      targetPort: 8383
  selector:
    io.fynarfin.service: service
status:
  loadBalancer: {}
