apiVersion: {{ .Values.persistentvolumeclaim.apiversion }}
kind: PersistentVolumeClaim
metadata:
  labels:
    io.fynarfin.service: service-claim1
  name: service-claim1
  namespace: odk  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
